import { serverSideTranslations } from 'next-i18next/serverSideTranslations';
import Head from 'next/head';
import dynamic from 'next/dynamic';
import { useEffect, useState } from 'react';
import { useRouter } from 'next/router';
import WheelBase from '@src/features/wheelBase';
import Hero from '@src/features/hero';
import ParallaxSectionThird from '@src/components/parallex3';
const ParallaxSection = dynamic(() => import('@src/components/parallex'), { ssr: false });
const ParallaxSectionSecond = dynamic(() => import('@src/components/parallex2'), { ssr: false });
const VRShowroom = dynamic(() => import('@src/modules/VRShowroom'), { ssr: false });
const TrimsSection = dynamic(() => import('@src/features/trims'), { ssr: false });

export default function Home () {
  const [mounted, setMounted] = useState(false);

  
  const router = useRouter();


  useEffect(() => {
    setMounted(true);
  }, []);

  if (!mounted) {
    return null; // or a loading state
  }



  return (
    <main className="relative">

      <Head>
        {router.locale == 'ar' ? <title>كيا سبورتاج - البروشور الرقمي</title> : <title>Kia sportage - Digital Brochure</title>}
        <link rel="icon" href="/kia.ico" />
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Hero />
      <WheelBase />
      <VRShowroom />
      <ParallaxSection />
      <ParallaxSectionThird />
      <TrimsSection />
      <ParallaxSectionSecond />
     

    </main>
  );
}

export async function getStaticProps ({ locale }) {
  return {
    props: {
      ...(await serverSideTranslations(locale, ['common'])),
    },
  };
}
